org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8 --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang=ALL-UNNAMED
android.useAndroidX=true
android.enableJetifier=true
android.defaults.buildfeatures.buildconfig=true
android.nonTransitiveRClass=false
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
